apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  selector: 
    matchLabels: 
      app: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo

    spec:
      containers:
        - name: mongo
          image: mongo
          imagePullPolicy: Always
          ports:
            - name: mongo
              containerPort: 27017
              protocol: TCP

          volumeMounts:
            - name: mongo-volume
              mountPath: /data/db

      volumes:
        - name: mongo-volume
          persistentVolumeClaim: 
            claimName: mongo-claim