---


# rabbitmq


- name: command 0
  shell: apt-get install curl gnupg apt-transport-https -y

- name: main sign key
  shell: curl -1sLf "https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA" | sudo gpg --dearmor | sudo tee /usr/share/keyrings/com.rabbitmq.team.gpg > /dev/null

- name: ppa erlang
  shell: curl -1sLf "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xf77f1eda57ebb1cc" | sudo gpg --dearmor | sudo tee /usr/share/keyrings/net.launchpad.ppa.rabbitmq.erlang.gpg > /dev/null

- name: rabbitmq repo
  shell: curl -1sLf "https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey" | sudo gpg --dearmor | sudo tee /usr/share/keyrings/io.packagecloud.rabbitmq.gpg > /dev/null


- name: add content0
  shell: echo {{ rabbitmq0 }}>>/etc/apt/sources.list.d/rabbitmq.list

- name: add content1
  shell: echo {{ rabbitmq1 }}>>/etc/apt/sources.list.d/rabbitmq.list

- name: add content2
  shell: echo {{ rabbitmq2 }}>>/etc/apt/sources.list.d/rabbitmq.list

- name: add content3
  shell: echo {{ rabbitmq3 }}>>/etc/apt/sources.list.d/rabbitmq.list


- name: update system
  shell: apt-get update -y

- name: erlang package
  shell: apt-get install -y erlang-base \
                        erlang-asn1 erlang-crypto erlang-eldap erlang-ftp erlang-inets \
                        erlang-mnesia erlang-os-mon erlang-parsetools erlang-public-key \
                        erlang-runtime-tools erlang-snmp erlang-ssl \
                        erlang-syntax-tools erlang-tftp erlang-tools erlang-xmerl
                    

- name: rabbitmq package
  shell: apt-get install rabbitmq-server -y --fix-missing

- name: enable rabbitmq management
  shell: rabbitmq-plugins enable rabbitmq_management

- name: rabbitmq user
  shell: rabbitmqctl add_user {{ username}} {{ password }}

- name: set as admin
  shell: rabbitmqctl set_user_tags rmqadmin administrator

- name: set admin permission
  shell: rabbitmqctl set_permissions -p / rmqadmin ".*" ".*" ".*"